export { default } from "./src/wallet-manager-spark.js";
export type SparkWalletConfig = import("./src/wallet-manager-spark.js").SparkWalletConfig;
export type WalletAccountSpark = import("./src/wallet-account-spark.js").default;
export type KeyPair = import("./src/wallet-account-spark.js").KeyPair;
export type SparkTransaction = import("./src/wallet-account-spark.js").SparkTransaction;
export type WalletLeaf = import("./src/wallet-account-spark.js").WalletLeaf;
export type CoopExitRequest = import("./src/wallet-account-spark.js").CoopExitRequest;
export type LightningReceiveRequest = import("./src/wallet-account-spark.js").LightningReceiveRequest;
export type LightningSendRequest = import("./src/wallet-account-spark.js").LightningSendRequest;
export type SparkTransfer = import("./src/wallet-account-spark.js").SparkTransfer;
