export { default } from "./src/wallet-manager-spark.js";
export { default as WalletAccountReadOnlySpark } from "./src/wallet-account-read-only-spark.js";
export { default as WalletAccountSpark } from "./src/wallet-account-spark.js";
export type NetworkType = import("@buildonspark/spark-sdk").NetworkType;
export type WithdrawParams = import("@buildonspark/spark-sdk").WithdrawParams;
export type CreateLightningInvoiceParams = import("@buildonspark/spark-sdk").CreateLightningInvoiceParams;
export type PayLightningInvoiceParams = import("@buildonspark/spark-sdk").PayLightningInvoiceParams;
export type SparkAddressFormat = import("@buildonspark/spark-sdk").SparkAddressFormat;
export type FulfillSparkInvoiceResponse = import("@buildonspark/spark-sdk").FulfillSparkInvoiceResponse;
export type WalletLeaf = import("@buildonspark/spark-sdk/types").WalletLeaf;
export type CoopExitRequest = import("@buildonspark/spark-sdk/types").CoopExitRequest;
export type CoopExitFeeQuote = import("@buildonspark/spark-sdk/types").CoopExitFeeQuote;
export type LightningReceiveRequest = import("@buildonspark/spark-sdk/types").LightningReceiveRequest;
export type LightningSendRequest = import("@buildonspark/spark-sdk/types").LightningSendRequest;
export type LightningSendFeeEstimateInput = import("@buildonspark/spark-sdk/types").LightningSendFeeEstimateInput;
export type SparkTransfer = import("@buildonspark/spark-sdk/types").WalletTransfer;
export type QuerySparkInvoicesResponse = import("@buildonspark/spark-sdk/proto/spark").QuerySparkInvoicesResponse;
export type SparkTransactionReceipt = import("@sparkscan/api-node-sdk-client").TxV1Response;
export type FeeRates = import("@tetherto/wdk-wallet").FeeRates;
export type KeyPair = import("@tetherto/wdk-wallet").KeyPair;
export type TransactionResult = import("@tetherto/wdk-wallet").TransactionResult;
export type TransferOptions = import("@tetherto/wdk-wallet").TransferOptions;
export type TransferResult = import("@tetherto/wdk-wallet").TransferResult;
export type SparkTransaction = import("./src/wallet-account-read-only-spark.js").SparkTransaction;
export type SparkWalletConfig = import("./src/wallet-account-read-only-spark.js").SparkWalletConfig;
export type WithdrawOptions = import("./src/wallet-account-spark.js").WithdrawOptions;
export type QuoteWithdrawOptions = import("./src/wallet-account-spark.js").QuoteWithdrawOptions;
export type GetTransfersOptions = import("./src/wallet-account-spark.js").GetTransfersOptions;
export type RefundStaticDepositOptions = import("./src/wallet-account-spark.js").RefundStaticDepositOptions;
export type CreateSatsInvoiceOptions = import("./src/wallet-account-spark.js").CreateSatsInvoiceOptions;
export type CreateTokensInvoiceOptions = import("./src/wallet-account-spark.js").CreateTokensInvoiceOptions;
export type SparkInvoice = import("./src/wallet-account-spark.js").SparkInvoice;
