export { default } from "./src/wallet-manager-spark.js";
export { default as WalletAccountReadOnlySpark } from "./src/wallet-account-read-only-spark.js";
export { default as WalletAccountSpark } from "./src/wallet-account-spark.js";
export { LightningPaymentError } from "./src/errors.js";
export type NetworkType = import("@buildonspark/spark-sdk").NetworkType;
export type SparkReadonlyClient = import("@buildonspark/spark-sdk").SparkReadonlyClient;
export type SparkTransfer = import("@buildonspark/spark-sdk/proto/spark").Transfer;
export type DepositAddressQueryResult = import("@buildonspark/spark-sdk/proto/spark").DepositAddressQueryResult;
export type InvoiceResponse = import("@buildonspark/spark-sdk/proto/spark").InvoiceResponse;
export type WithdrawParams = import("@buildonspark/spark-sdk").WithdrawParams;
export type CreateLightningInvoiceParams = import("@buildonspark/spark-sdk").CreateLightningInvoiceParams;
export type PayLightningInvoiceParams = import("@buildonspark/spark-sdk").PayLightningInvoiceParams;
export type SparkAddressFormat = import("@buildonspark/spark-sdk").SparkAddressFormat;
export type FulfillSparkInvoiceResponse = import("@buildonspark/spark-sdk").FulfillSparkInvoiceResponse;
export type WalletLeaf = import("@buildonspark/spark-sdk/types").WalletLeaf;
export type CoopExitRequest = import("@buildonspark/spark-sdk/types").CoopExitRequest;
export type CoopExitFeeQuote = import("@buildonspark/spark-sdk/types").CoopExitFeeQuote;
export type LightningReceiveRequest = import("@buildonspark/spark-sdk/types").LightningReceiveRequest;
export type LightningSendRequest = import("@buildonspark/spark-sdk/types").LightningSendRequest;
export type LightningSendFeeEstimateInput = import("@buildonspark/spark-sdk/types").LightningSendFeeEstimateInput;
export type FeeRates = import("@tetherto/wdk-wallet").FeeRates;
export type KeyPair = import("@tetherto/wdk-wallet").KeyPair;
export type TransactionResult = import("@tetherto/wdk-wallet").TransactionResult;
export type TransferOptions = import("@tetherto/wdk-wallet").TransferOptions;
export type TransferResult = import("@tetherto/wdk-wallet").TransferResult;
export type Finality = import("@tetherto/wdk-wallet").Finality;
export type TransactionReceipt = import("@tetherto/wdk-wallet").TransactionReceipt;
export type WaitForTransactionTarget = import("@tetherto/wdk-wallet").WaitForTransactionTarget;
export type WaitForTransactionOptions = import("@tetherto/wdk-wallet").WaitForTransactionOptions;
export type SparkTransaction = import("./src/wallet-account-read-only-spark.js").SparkTransaction;
export type SparkTransactionDetails = import("./src/wallet-account-read-only-spark.js").SparkTransactionDetails;
export type SparkWalletConfig = import("./src/wallet-account-read-only-spark.js").SparkWalletConfig;
export type GetTransfersOptions = import("./src/wallet-account-read-only-spark.js").GetTransfersOptions;
export type QueryDepositAddressesParams = import("@buildonspark/spark-sdk").QueryDepositAddressesParams;
export type GetUtxosParams = import("@buildonspark/spark-sdk").GetUtxosParams;
export type QuerySparkInvoicesParams = import("@buildonspark/spark-sdk").QuerySparkInvoicesParams;
export type WithdrawOptions = import("./src/wallet-account-spark.js").WithdrawOptions;
export type QuoteWithdrawOptions = import("./src/wallet-account-spark.js").QuoteWithdrawOptions;
export type RefundStaticDepositOptions = import("./src/wallet-account-spark.js").RefundStaticDepositOptions;
export type CreateSatsInvoiceOptions = import("./src/wallet-account-spark.js").CreateSatsInvoiceOptions;
export type CreateTokensInvoiceOptions = import("./src/wallet-account-spark.js").CreateTokensInvoiceOptions;
export type SparkInvoice = import("./src/wallet-account-spark.js").SparkInvoice;
export type LightningPaymentErrorOptions = import("./src/errors.js").LightningPaymentErrorOptions;
