export { default } from "./src/wallet-manager-spark.js";
export { default as WalletAccountReadOnlySpark } from "./src/wallet-account-read-only-spark.js";
export { default as WalletAccountSpark } from "./src/wallet-account-spark.js";
export type NetworkType = import("@buildonspark/spark-sdk").NetworkType;
export type WalletLeaf = import("@buildonspark/spark-sdk/types").WalletLeaf;
export type CoopExitRequest = import("@buildonspark/spark-sdk/types").CoopExitRequest;
export type LightningReceiveRequest = import("@buildonspark/spark-sdk/types").LightningReceiveRequest;
export type LightningSendRequest = import("@buildonspark/spark-sdk/types").LightningSendRequest;
export type SparkTransfer = import("@buildonspark/spark-sdk/types").WalletTransfer;
export type SparkTransactionReceipt = import("@sparkscan/api-node-sdk-client").TxV1Response;
export type FeeRates = import("@wdk/wallet").FeeRates;
export type KeyPair = import("@wdk/wallet").KeyPair;
export type TransactionResult = import("@wdk/wallet").TransactionResult;
export type TransferOptions = import("@wdk/wallet").TransferOptions;
export type TransferResult = import("@wdk/wallet").TransferResult;
export type SparkTransaction = import("./src/wallet-account-read-only-spark.js").SparkTransaction;
export type SparkWalletConfig = import("./src/wallet-account-read-only-spark.js").SparkWalletConfig;
